default: &default
  adapter: postgresql
  encoding: unicode
  username: 'neznauy'
  password: 'neznauy'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: neznauy

test:
  <<: *default
  database: neznauy_test

production:
  <<: *default
  database: neznauy_prod